-- ============================================================
-- NIL Perfumes - Database Schema
-- Version: 1.1
-- Run this script in Lovable Cloud → Database (SQL Editor)
-- ============================================================

-- ============================================================
-- PART 1: ENUMS (Type Definitions)
-- ============================================================

-- הרשאות משתמשים במערכת הניהול
create type public.app_role as enum ('admin', 'moderator');

-- סטטוסים קשיחים להזמנה
create type public.order_status as enum (
  'pending',    -- נוצר, ממתין לתשלום
  'paid',       -- שולם בהצלחה
  'processing', -- בטיפול/אריזה
  'shipped',    -- יצא למשלוח
  'delivered',  -- נמסר
  'cancelled',  -- בוטל
  'refunded'    -- הוחזר כסף
);

-- סוגי הנחות לקופונים
create type public.discount_type as enum ('percent', 'fixed');


-- ============================================================
-- PART 2: HELPER FUNCTIONS
-- ============================================================

-- פונקציה לעדכון אוטומטי של updated_at
create or replace function public.update_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- פונקציה לבדיקת הרשאות אדמין
create or replace function public.has_role(_role app_role)
returns boolean as $$
  select exists (
    select 1 from public.user_roles
    where user_id = auth.uid()
    and role = _role
  );
$$ language sql security definer;

-- פונקציה לבדיקה אם המשתמש הוא אדמין
create or replace function public.is_admin()
returns boolean as $$
  select public.has_role('admin');
$$ language sql security definer;


-- ============================================================
-- PART 3: CORE TABLES
-- ============================================================

-- -----------------------------------------------------------
-- 3.1 Products (מוצרים)
-- -----------------------------------------------------------
create table public.products (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  description text,
  price numeric not null check (price >= 0),
  image_url text,
  in_stock boolean default true,
  display_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Trigger לעדכון updated_at
create trigger products_updated_at
  before update on public.products
  for each row execute function public.update_updated_at();

-- אינדקסים
create index idx_products_slug on public.products(slug);
create index idx_products_in_stock on public.products(in_stock);
create index idx_products_display_order on public.products(display_order);


-- -----------------------------------------------------------
-- 3.2 Customers (לקוחות)
-- -----------------------------------------------------------
create table public.customers (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  full_name text,
  phone text,
  total_orders int default 0,
  total_spent numeric default 0,
  last_order_at timestamptz,
  created_at timestamptz default now()
);

-- אינדקסים
create index idx_customers_email on public.customers(email);


-- -----------------------------------------------------------
-- 3.3 Shipping Options (אפשרויות משלוח)
-- -----------------------------------------------------------
create table public.shipping_options (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  price numeric default 0,
  is_active boolean default true,
  display_order int default 0
);


-- -----------------------------------------------------------
-- 3.4 Coupons (קופונים)
-- -----------------------------------------------------------
create table public.coupons (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  discount_type public.discount_type not null,
  discount_value numeric not null check (discount_value > 0),
  min_order_amount numeric default 0,
  max_uses int,
  usage_count int default 0,
  expires_at timestamptz,
  is_active boolean default true,
  created_at timestamptz default now()
);

-- אינדקס
create index idx_coupons_code on public.coupons(code);


-- -----------------------------------------------------------
-- 3.5 Orders (הזמנות)
-- -----------------------------------------------------------
create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity (start with 1000),
  
  -- קישור ללקוח + snapshot
  customer_id uuid references public.customers(id) on delete restrict,
  customer_email text not null,
  
  -- פרטי מקבל המשלוח (Flat Fields)
  recipient_name text not null,
  phone text not null,
  city text not null,
  street text not null,
  house_number text not null,
  apartment text,
  zip_code text,
  notes text,

  -- משלוח
  shipping_option_id uuid references public.shipping_options(id),
  shipping_cost numeric not null default 0,
  
  -- סיכום פיננסי
  products_total numeric not null,
  discount_amount numeric default 0,
  coupon_code text,
  total_amount numeric not null,
  
  -- סטטוס ותשלום
  status public.order_status not null default 'pending',
  payment_provider_id text,
  
  -- תאריכים
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Trigger לעדכון updated_at
create trigger orders_updated_at
  before update on public.orders
  for each row execute function public.update_updated_at();

-- אינדקסים
create index idx_orders_customer_id on public.orders(customer_id);
create index idx_orders_status on public.orders(status);
create index idx_orders_created_at on public.orders(created_at desc);
create index idx_orders_order_number on public.orders(order_number);


-- -----------------------------------------------------------
-- 3.6 Order Items (פריטי הזמנה)
-- -----------------------------------------------------------
create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid references public.orders(id) on delete cascade not null,
  product_id uuid references public.products(id) on delete set null,
  
  -- נתונים היסטוריים (Snapshot)
  name text not null,
  price_at_purchase numeric not null,
  quantity int not null default 1 check (quantity > 0)
);

-- אינדקס
create index idx_order_items_order_id on public.order_items(order_id);


-- -----------------------------------------------------------
-- 3.7 User Roles (הרשאות ניהול)
-- -----------------------------------------------------------
create table public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade not null,
  role public.app_role not null,
  created_at timestamptz default now(),
  unique (user_id, role)
);

-- אינדקס
create index idx_user_roles_user_id on public.user_roles(user_id);


-- ============================================================
-- PART 4: ROW LEVEL SECURITY (RLS)
-- ============================================================

-- הפעלת RLS על כל הטבלאות
alter table public.products enable row level security;
alter table public.customers enable row level security;
alter table public.shipping_options enable row level security;
alter table public.coupons enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.user_roles enable row level security;


-- -----------------------------------------------------------
-- 4.1 Products Policies
-- -----------------------------------------------------------

-- כולם יכולים לקרוא מוצרים
create policy "Public can read products"
  on public.products for select
  using (true);

-- רק אדמין יכול לערוך מוצרים
create policy "Admin can manage products"
  on public.products for all
  using (public.is_admin())
  with check (public.is_admin());


-- -----------------------------------------------------------
-- 4.2 Customers Policies
-- -----------------------------------------------------------

-- כולם יכולים ליצור לקוח (בעת הזמנה)
create policy "Public can create customers"
  on public.customers for insert
  with check (true);

-- רק אדמין יכול לקרוא לקוחות
create policy "Admin can read customers"
  on public.customers for select
  using (public.is_admin());

-- רק אדמין יכול לעדכן לקוחות
create policy "Admin can update customers"
  on public.customers for update
  using (public.is_admin());


-- -----------------------------------------------------------
-- 4.3 Shipping Options Policies
-- -----------------------------------------------------------

-- כולם יכולים לקרוא אפשרויות משלוח פעילות
create policy "Public can read active shipping options"
  on public.shipping_options for select
  using (is_active = true);

-- אדמין יכול לקרוא הכל
create policy "Admin can read all shipping options"
  on public.shipping_options for select
  using (public.is_admin());

-- רק אדמין יכול לנהל
create policy "Admin can manage shipping options"
  on public.shipping_options for all
  using (public.is_admin())
  with check (public.is_admin());


-- -----------------------------------------------------------
-- 4.4 Coupons Policies
-- -----------------------------------------------------------

-- כולם יכולים לקרוא קופונים פעילים (לצורך בדיקה)
create policy "Public can read active coupons"
  on public.coupons for select
  using (is_active = true);

-- אדמין יכול לקרוא הכל
create policy "Admin can read all coupons"
  on public.coupons for select
  using (public.is_admin());

-- רק אדמין יכול לנהל קופונים
create policy "Admin can manage coupons"
  on public.coupons for all
  using (public.is_admin())
  with check (public.is_admin());


-- -----------------------------------------------------------
-- 4.5 Orders Policies
-- -----------------------------------------------------------

-- כולם יכולים ליצור הזמנה
create policy "Public can create orders"
  on public.orders for insert
  with check (true);

-- רק אדמין יכול לקרוא הזמנות
create policy "Admin can read orders"
  on public.orders for select
  using (public.is_admin());

-- רק אדמין יכול לעדכן הזמנות
create policy "Admin can update orders"
  on public.orders for update
  using (public.is_admin());


-- -----------------------------------------------------------
-- 4.6 Order Items Policies
-- -----------------------------------------------------------

-- כולם יכולים ליצור פריטי הזמנה
create policy "Public can create order items"
  on public.order_items for insert
  with check (true);

-- רק אדמין יכול לקרוא פריטי הזמנות
create policy "Admin can read order items"
  on public.order_items for select
  using (public.is_admin());


-- -----------------------------------------------------------
-- 4.7 User Roles Policies
-- -----------------------------------------------------------

-- רק אדמין יכול לנהל הרשאות
create policy "Admin can manage user roles"
  on public.user_roles for all
  using (public.is_admin())
  with check (public.is_admin());

-- משתמש יכול לקרוא את ההרשאות שלו עצמו
create policy "Users can read own roles"
  on public.user_roles for select
  using (auth.uid() = user_id);


-- ============================================================
-- PART 5: SEED DATA (Optional)
-- ============================================================

-- אפשרויות משלוח התחלתיות
insert into public.shipping_options (name, price, is_active, display_order) values
  ('שליח עד הבית', 35, true, 1),
  ('איסוף עצמי', 0, true, 2);


-- ============================================================
-- END OF SCHEMA
-- ============================================================
